const AI_URLS = { chatgpt: "https://chatgpt.com/", claude: "https://claude.ai/new", gemini: "https://gemini.google.com/app", grok: "https://grok.com/" };
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.type === "select-region") { chooseRegion(sender.tab?.id, message.target).then(() => sendResponse({ ok: true })).catch(error => sendResponse({ ok: false, error: error.message })); return true; }
  if (message.type === "capture") { capture(message, sendResponse); return true; }
});
function capture(message, sendResponse) { chrome.tabs.captureVisibleTab({ format: "png" }, async (dataUrl) => { try { if (chrome.runtime.lastError || !dataUrl) throw new Error(chrome.runtime.lastError?.message || "Capture failed."); if (message.region) dataUrl = await offscreen("crop", { dataUrl, region: message.region }); if (message.target === "download") { await chrome.downloads.download({ url: dataUrl, filename: `CaptureAsk-${dateStamp()}.png`, saveAs: true }); sendResponse({ ok: true, action: "downloaded" }); return; } if (AI_URLS[message.target]) { await chrome.storage.session.set({ pendingCapture: dataUrl }); const tab = await chrome.tabs.create({ url: AI_URLS[message.target], active: true }); const focusPromise = focusAiInput(tab.id); const attachPromise = attachCapture(tab.id, dataUrl); let copied = true; try { await offscreen("copy", { dataUrl }); } catch { copied = false; } const [focused, attached] = await Promise.all([focusPromise, attachPromise]); sendResponse({ ok: true, action: attached ? "attached" : copied ? "copied" : "opened-without-copy", focused }); return; } throw new Error("Unknown destination."); } catch (error) { sendResponse({ ok: false, error: error.message }); } }); }
async function chooseRegion(tabId, target) { if (!tabId) [{ id: tabId }] = await chrome.tabs.query({ active: true, lastFocusedWindow: true }); if (!tabId) throw new Error("Active tab not found."); const [{ result: region }] = await chrome.scripting.executeScript({ target: { tabId }, func: selectArea }); if (region) capture({ target, region }, () => {}); }
async function offscreen(action, payload) { const contexts = await chrome.runtime.getContexts({ contextTypes: ["OFFSCREEN_DOCUMENT"], documentUrls: [chrome.runtime.getURL("offscreen.html")] }); if (!contexts.length) await chrome.offscreen.createDocument({ url: "offscreen.html", reasons: ["CLIPBOARD"], justification: "Copy a user-requested screenshot to the clipboard." }); const response = await chrome.runtime.sendMessage({ target: "offscreen", action, ...payload }); if (!response?.ok) throw new Error(response?.error || "Screenshot processing failed."); return response.dataUrl || payload.dataUrl; }
async function focusAiInput(tabId) { for (let attempt = 0; attempt < 20; attempt += 1) { await new Promise(resolve => setTimeout(resolve, 600)); try { const response = await chrome.tabs.sendMessage(tabId, { type: "focus-ai-input" }); if (response?.ok) return true; } catch { /* The content script is not ready while the AI page loads. */ } } return false; }
async function attachCapture(tabId, dataUrl) { for (let attempt = 0; attempt < 20; attempt += 1) { await new Promise(resolve => setTimeout(resolve, 600)); try { const response = await chrome.tabs.sendMessage(tabId, { type: "attach-capture", dataUrl }); if (response?.ok) return true; } catch { /* The content script is not ready while the AI page loads. */ } } return false; }
function focusChatBox() { const selectors = ['textarea', '[contenteditable="true"]', '[role="textbox"]']; const input = selectors.flatMap(selector => [...document.querySelectorAll(selector)]).find(element => { const style = getComputedStyle(element); return !element.disabled && style.visibility !== 'hidden' && style.display !== 'none' && element.getBoundingClientRect().width > 20; }); if (!input) return false; input.scrollIntoView({ block: 'center' }); input.focus({ preventScroll: true }); input.click(); return document.activeElement === input || input.contains(document.activeElement); }
function selectArea() { return new Promise(resolve => { const overlay=document.createElement("div"),box=document.createElement("div"),hint=document.createElement("div"); Object.assign(overlay.style,{position:"fixed",inset:"0",zIndex:"2147483647",cursor:"crosshair",background:"rgba(9,12,25,.28)"});Object.assign(box.style,{position:"fixed",border:"2px solid #c8ff4a",background:"rgba(200,255,74,.12)",display:"none"});Object.assign(hint.style,{position:"fixed",top:"18px",left:"50%",transform:"translateX(-50%)",padding:"9px 13px",borderRadius:"8px",background:"#10152d",color:"#fff",font:"13px sans-serif"});hint.textContent="드래그하여 캡처 영역을 선택하세요 · Esc 취소";overlay.append(box,hint);document.documentElement.append(overlay);let start;const clear=()=>overlay.remove();overlay.addEventListener("pointerdown",e=>{start={x:e.clientX,y:e.clientY};box.style.display="block";});overlay.addEventListener("pointermove",e=>{if(!start)return;const x=Math.min(start.x,e.clientX),y=Math.min(start.y,e.clientY),w=Math.abs(e.clientX-start.x),h=Math.abs(e.clientY-start.y);Object.assign(box.style,{left:x+"px",top:y+"px",width:w+"px",height:h+"px"});});overlay.addEventListener("pointerup",e=>{if(!start)return;const x=Math.min(start.x,e.clientX),y=Math.min(start.y,e.clientY),width=Math.abs(e.clientX-start.x),height=Math.abs(e.clientY-start.y);clear();resolve(width>4&&height>4?{x,y,width,height,scale:devicePixelRatio}:null);});addEventListener("keydown",function esc(e){if(e.key==="Escape"){clear();removeEventListener("keydown",esc);resolve(null);}},{once:true}); }); }
function dateStamp(){ return new Date().toISOString().replace(/[:.]/g,"-"); }
